// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID         int32  `json:"id"`
	AuthorName string `json:"author_name"`
}

type Book struct {
	ID            string `json:"id"`
	Title         string `json:"title"`
	AuthorName    string `json:"author_name"`
	DatePublished string `json:"date_published"`
	Description   string `json:"description"`
}

type BookCopies struct {
	ID            string `json:"id"`
	BookID        string `json:"book_id"`
	Title         string `json:"title"`
	AuthorName    string `json:"author_name"`
	DatePublished string `json:"date_published"`
	Description   string `json:"description"`
	BookStatus    string `json:"book_status"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}
