create type "public"."book_status_enum" as enum ('Available', 'In use', 'Borrowed', 'Not Available');

create table "public"."authors" (
    "id" bigint generated by default as identity not null,
    "author_name" character varying not null
);


alter table "public"."authors" enable row level security;

create table "public"."book_copies" (
    "id" bigint generated by default as identity not null,
    "book_id" uuid not null default gen_random_uuid(),
    "book_status" book_status_enum default 'Available'::book_status_enum
);


alter table "public"."book_copies" enable row level security;

create table "public"."books" (
    "id" uuid not null default gen_random_uuid(),
    "title" character varying not null,
    "author_id" bigint,
    "date_published" date,
    "description" text
);


alter table "public"."books" enable row level security;

CREATE UNIQUE INDEX authors_pkey ON public.authors USING btree (id);

CREATE UNIQUE INDEX book_copies_pkey ON public.book_copies USING btree (id);

CREATE UNIQUE INDEX books_pkey ON public.books USING btree (id);

alter table "public"."authors" add constraint "authors_pkey" PRIMARY KEY using index "authors_pkey";

alter table "public"."book_copies" add constraint "book_copies_pkey" PRIMARY KEY using index "book_copies_pkey";

alter table "public"."books" add constraint "books_pkey" PRIMARY KEY using index "books_pkey";

alter table "public"."book_copies" add constraint "book_copies_book_id_fkey" FOREIGN KEY (book_id) REFERENCES books(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."book_copies" validate constraint "book_copies_book_id_fkey";

alter table "public"."books" add constraint "books_author_id_fkey" FOREIGN KEY (author_id) REFERENCES authors(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."books" validate constraint "books_author_id_fkey";

grant delete on table "public"."authors" to "anon";

grant insert on table "public"."authors" to "anon";

grant references on table "public"."authors" to "anon";

grant select on table "public"."authors" to "anon";

grant trigger on table "public"."authors" to "anon";

grant truncate on table "public"."authors" to "anon";

grant update on table "public"."authors" to "anon";

grant delete on table "public"."authors" to "authenticated";

grant insert on table "public"."authors" to "authenticated";

grant references on table "public"."authors" to "authenticated";

grant select on table "public"."authors" to "authenticated";

grant trigger on table "public"."authors" to "authenticated";

grant truncate on table "public"."authors" to "authenticated";

grant update on table "public"."authors" to "authenticated";

grant delete on table "public"."authors" to "service_role";

grant insert on table "public"."authors" to "service_role";

grant references on table "public"."authors" to "service_role";

grant select on table "public"."authors" to "service_role";

grant trigger on table "public"."authors" to "service_role";

grant truncate on table "public"."authors" to "service_role";

grant update on table "public"."authors" to "service_role";

grant delete on table "public"."book_copies" to "anon";

grant insert on table "public"."book_copies" to "anon";

grant references on table "public"."book_copies" to "anon";

grant select on table "public"."book_copies" to "anon";

grant trigger on table "public"."book_copies" to "anon";

grant truncate on table "public"."book_copies" to "anon";

grant update on table "public"."book_copies" to "anon";

grant delete on table "public"."book_copies" to "authenticated";

grant insert on table "public"."book_copies" to "authenticated";

grant references on table "public"."book_copies" to "authenticated";

grant select on table "public"."book_copies" to "authenticated";

grant trigger on table "public"."book_copies" to "authenticated";

grant truncate on table "public"."book_copies" to "authenticated";

grant update on table "public"."book_copies" to "authenticated";

grant delete on table "public"."book_copies" to "service_role";

grant insert on table "public"."book_copies" to "service_role";

grant references on table "public"."book_copies" to "service_role";

grant select on table "public"."book_copies" to "service_role";

grant trigger on table "public"."book_copies" to "service_role";

grant truncate on table "public"."book_copies" to "service_role";

grant update on table "public"."book_copies" to "service_role";

grant delete on table "public"."books" to "anon";

grant insert on table "public"."books" to "anon";

grant references on table "public"."books" to "anon";

grant select on table "public"."books" to "anon";

grant trigger on table "public"."books" to "anon";

grant truncate on table "public"."books" to "anon";

grant update on table "public"."books" to "anon";

grant delete on table "public"."books" to "authenticated";

grant insert on table "public"."books" to "authenticated";

grant references on table "public"."books" to "authenticated";

grant select on table "public"."books" to "authenticated";

grant trigger on table "public"."books" to "authenticated";

grant truncate on table "public"."books" to "authenticated";

grant update on table "public"."books" to "authenticated";

grant delete on table "public"."books" to "service_role";

grant insert on table "public"."books" to "service_role";

grant references on table "public"."books" to "service_role";

grant select on table "public"."books" to "service_role";

grant trigger on table "public"."books" to "service_role";

grant truncate on table "public"."books" to "service_role";

grant update on table "public"."books" to "service_role";


