// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Fine struct {
	FineID     string  `json:"fine_id"`
	PatronID   string  `json:"patronId"`
	BookID     string  `json:"bookId"`
	DaysLate   int32   `json:"daysLate"`
	RatePerDay float64 `json:"ratePerDay"`
	Amount     float64 `json:"amount"`
	CreatedAt  string  `json:"createdAt"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}
