// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Fine struct {
	ID         string  `json:"id"`
	DaysLate   int32   `json:"daysLate"`
	RatePerDay float64 `json:"ratePerDay"`
	Amount     float64 `json:"amount"`
}

type Mutation struct {
}

type Query struct {
}
