// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Patron struct {
	PatronID      string `json:"patron_id"`
	FirstName     string `json:"first_name"`
	LastName      string `json:"last_name"`
	PhoneNumber   string `json:"phone_number"`
	PatronCreated string `json:"patron_created"`
}

type Query struct {
}

type Subscription struct {
}
